
a. creating nd arrays

b. subsetting with indicws and conditions

c.comparison with np and math functions (np.sqrt, log), special numpy functions

In [1]:
import numpy as np

In [3]:
b=np.array([  [3,4,5],[4,5,6],[6,7,8],[7,8,9]  ])
b

array([[3, 4, 5],
       [4, 5, 6],
       [6, 7, 8],
       [7, 8, 9]])

In [5]:
b.shape

(4, 3)

In [9]:
#assymetric arrays
c=np.array([  [3,5],[4,5,6],[6],[7,8,9]  ])
c

C:\Users\aruna\AppData\Local\Temp\ipykernel_1292\274666058.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([  [3,5],[4,5,6],[6],[7,8,9]  ])


array([list([3, 5]), list([4, 5, 6]), list([6]), list([7, 8, 9])],
      dtype=object)

In [10]:
c.shape 

(4,)

## extracting elements and indice operations

In [42]:
b

array([[  3,   4, -99],
       [  4,   5,  99],
       [  6,   0,   8],
       [  7,   8,   9]])

In [43]:
#extracting elements
b[2,1]

0

In [44]:
b[:,1]

array([4, 5, 0, 8])

In [45]:
b[1]

array([ 4,  5, 99])

In [46]:
b[[0,2,1],[2,1,2]] #will get paired [0,2],[2,1],[1,2]
#multiple indices not possible in lists

array([-99,   0,  99])

In [47]:
b[[0,2,1],[2,1,2]] = [-99,0,-99]
b

array([[  3,   4, -99],
       [  4,   5, -99],
       [  6,   0,   8],
       [  7,   8,   9]])

In [48]:
b>0

array([[ True,  True, False],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [49]:
b[b>0] #returns all the numbers after indivudual check of elements with condition

array([3, 4, 4, 5, 6, 8, 7, 8, 9])

In [50]:
b[:,2]>=0

array([False, False,  True,  True])

In [51]:
print(b)
b[b[:,2]>=0,:] #these type of things are much easier in pandas

[[  3   4 -99]
 [  4   5 -99]
 [  6   0   8]
 [  7   8   9]]


array([[6, 0, 8],
       [7, 8, 9]])

## Math functions

Math functions only work for single values and not for arrays. 
There are numpy counter parts which solve this problem

In [52]:
import math as m



In [53]:
b[1]=m.fabs(b[1])

TypeError: only size-1 arrays can be converted to Python scalars

In [58]:
print(b)
b[1]=np.fabs(b[1])
b[1]

[[  3   4 -99]
 [  4   5  99]
 [  6   0   8]
 [  7   8   9]]


array([ 4,  5, 99])

In [59]:
np.sum(b)

54

In [60]:
#row sums
np.sum(b,axis=1) 

array([-92, 108,  14,  24])

In [61]:
#column sums
np.sum(b,axis=0) 

array([20, 17, 17])

## generating data 

In [62]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [63]:
for i in np.arange(6):
    print (i)

0
1
2
3
4
5


In [67]:
np.linspace(start=1,stop=4,num=10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

## generating random data